---
apiVersion: v1
kind: Secret
metadata:
  name: fwk-secret
  labels: 
    app: fwkapp

data:
  ROOT_PASSWORD: Y2hhbmdlaXQ= 

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: fwk-cluster
  labels: 
    app: fwkapp

spec:
  replicas: 2
  secretName: fwk-secret
  persistentVolumeClaims:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: do-block-storage 

