---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-po
  namespace: fortune-ns
  labels:
    app: fortune

spec:
  containers:
  - name: fortune-container
    image: chukmunnlee/fortune:v1
    #wombat001docker/fortune:v0.01
    imagePullPolicy: IfNotPresent 
    ports:
    - containerPort: 3000