---
apiVersion: v1
kind: Secret
metadata:
  name: nw-secret
  labels: 
    app: northwind

data:
  MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ= 
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
   name: nwdb-deploy
   labels:
      app: northwind

spec:
   replicas: 1 # dbs are stateful, so there should be one
   selector:
      matchLabels:
         app: northwind
   #minReadySeconds: 30
   template:
      metadata:
         name: nwdb-pod
         labels:
            app: northwind
      spec:
         containers:
         - name: nwdb-container
           image: stackupiss/northwind-db:v1
           #image: chukmunnlee/my-nwdb:v3
           imagePullPolicy: IfNotPresent
           envFrom:
           - secretRef: 
              name: nw-secret
           ports:
           - name: nwdb-port
             containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: nwdb-svc
  labels: 
     app: northwind

spec:
  type: ClusterIP
  selector:
    app: northwind
  ports:
  - port: 3306
    targetPort: nwdb-port


        
